apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaciones-service
  labels:
    app: notificaciones-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificaciones-service
  template:
    metadata:
      labels:
        app: notificaciones-service
    spec:
      containers:
        - name: notificaciones-service
          image: notificaciones-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: sistema-tickets
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: fernando192001
---
apiVersion: v1
kind: Service
metadata:
  name: notificaciones-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: notificaciones-service
  type: ClusterIP
